services:
  ros-humble-container:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
    container_name: ros-humble-container
    command: tail -f /dev/null
    network_mode: host
    ports:
      - 6080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}  
      - QT_X11_NO_MITSHM=1    
      - ROS_DOMAIN_ID=17
      - ROS_LOCALHOST_ONLY=0
      - CYCLONEDDS_URI=file:///data/cyclonedds.xml
    volumes:
      - ./:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /home/mehdi-khorasani/copy-of-dri-for-docker:/dev/dri
    extra_hosts:
    - "host.docker.internal:host-gateway"

  pcl-dev-container:
    build:
      context: .           # directory with your Dockerfile
      dockerfile: point-cloud-infra/Dockerfile
    container_name: pcl-dev-container
    command: python3 /data/point-cloud-infra/server.py
    ports:
      - 6082:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    runtime: nvidia   # for legacy Compose (optional but safe)

  mysql:
      image: mysql:8.0
      container_name: stair_mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: stairs_db
        MYSQL_USER: stairuser
        MYSQL_PASSWORD: stairpass
      ports:
        - "6083:3306"
      volumes:
        - ./mysql_data:/var/lib/mysql

  decree-compliance-checker:
    build:
      context: ./decree-compliance       # directory with your Dockerfile
      dockerfile: Dockerfile
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    container_name: decree-compliance-checker
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app

    volumes:
      - ./decree-compliance/app:/app

