# Each node has its own section with all its topics, subscribers, publishers, services, and clients.

env:
  simulation: true

db_reader:
  services:
    get_stair_case_metrics: "get_stair_case_metrics"

orchestrator:
  subscribers:
    save_point_request: "/save_pt_request"
    save_and_process_point_request: "/save_and_process_pt_request"

  publishers:
    stairs_calculated_metrics: "/stairs_calculated_metrics"
    pc_saved_response: "/pc_saved_response"
    stairs_compliance_status: "/stairs_compliance_status"

  clients:
    save_pointcloud: "save_pointcloud"
    get_stair_case_metrics: "get_stair_case_metrics"

pc_saver:
  subscribers:
    #use the first ones for simulation, consecutive for real robot
    camera_depth_points: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/points"
    # camera_depth_points: "/camera/camera/depth/color/points"
    # camera_depth_points: "/manuallycomputed/points"
    
    camera_color_image: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/image"
    # camera_color_image: "/camera/camera/color/image_raw"
    
    camera_depth_info: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/camera_info"
    # camera_depth_info: "/camera/camera/depth/camera_info"

  services:
    save_pointcloud: "save_pointcloud"

rviz_panel_tutorial:
  subscribers:
    stairs_calculated_metrics: "/stairs_calculated_metrics"
    stairs_compliance_status: "/stairs_compliance_status"
    save_point_request: "/save_pt_request"
    save_and_process_point_request: "/save_and_process_pt_request"

pointcloud_maker:
  topics:
    image: "/camera/camera/color/image_raw"
    depth_image: "/camera/camera/aligned_depth_to_color/image_raw"
    camera_info: "/camera/camera/color/camera_info"
    point_cloud: "/manuallycomputed/points"
