# Each node has its own section with all its topics, subscribers, publishers, services, and clients.

# set to false when using real robot (other variables need to changed, please go down and follow instructions):
env:
  simulation: false

db_reader:
  services:
    get_stair_case_metrics: "get_stair_case_metrics"

orchestrator:
  subscribers:
    save_point_request: "/save_pt_request"
    save_and_process_point_request: "/save_and_process_pt_request"

  publishers:
    stairs_calculated_metrics: "/stairs_calculated_metrics"
    pc_saved_response: "/pc_saved_response"
    stairs_compliance_status: "/stairs_compliance_status"

  clients:
    save_pointcloud: "save_pointcloud"
    get_stair_case_metrics: "get_stair_case_metrics"

pc_saver:
  subscribers:
    #ONLY FOR REAL ROBOT: uncomment this one if pointcloud is being published by realsense node directly:
    # camera_depth_points: "/camera/camera/depth/color/points"


    #FOR SIMULATION:
    # camera_depth_points: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/points"
    # camera_color_image: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/image"
    # camera_depth_info: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/camera_info"

    # #FOR REAL ROBOT:
    camera_depth_points: "/manuallycomputed/points"
    camera_color_image: "/camera/camera/color/image_raw"
    camera_depth_info: "/camera/camera/depth/camera_info"
    # camera_depth_info: "/camera/camera/color/camera_info"
  services:
    save_pointcloud: "save_pointcloud"

rviz_panel_tutorial:
  subscribers:
    stairs_calculated_metrics: "/stairs_calculated_metrics"
    stairs_compliance_status: "/stairs_compliance_status"
    save_point_request: "/save_pt_request"
    save_and_process_point_request: "/save_and_process_pt_request"

pointcloud_maker:
  topics:
    image: "/camera/camera/color/image_raw"
    depth_image: "/camera/camera/aligned_depth_to_color/image_raw"
    camera_info: "/camera/camera/color/camera_info"
    point_cloud: "/manuallycomputed/points"

pipeline:
  topics:
    pointcloud: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/points"
    depth_image: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/depth_image"
    image: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/image"
    image_info: "/world/default/model/turtlebot4/link/oakd_rgb_camera_frame/sensor/rgbd_camera/camera_info"
    
    gz_pointcloud: "sensor_msgs/msg/PointCloud2[ignition.msgs.PointCloudPacked"
    gz_image: "sensor_msgs/msg/Image[ignition.msgs.Image"
    gz_depth_image: "sensor_msgs/msg/Image[ignition.msgs.Image"
    gz_image_info: "sensor_msgs/msg/CameraInfo[ignition.msgs.CameraInfo"
  
  robot:
    x: -2.0
    y: -4.0
    z: 0
    yaw: 0
